gector_deberta_large:
  type: gector
  backend: triton
  serving_config:
    triton_host: triton-server
    triton_port: 8022
    pretrained_model_name_or_path: "gotutiyan/gector-deberta-large-5k"
    triton_model_name: gector_deberta_large
    device: cuda # cpu, cuda, or auto

coedit_large:
  type: coedit
  backend: triton
  serving_config:
    triton_host: triton-server
    triton_port: 8022
    pretrained_model_name_or_path: "rayliuca/coedit-large-onnx"
    # pretrained_model_name_or_path: "rayliuca/coedit-large-onnx-quantized" # cpu only!
    triton_model_name: coedit_large
    backend: ort
    device: cuda # cpu, cuda, or auto
  model_init_config:
    batch_size: 8
  model_inference_config:
    temperature: 0.8
  grammared_config:
    prompt_template: "Fix grammatical errors: {{ text }}"
